# .github/workflows/latex-release.yml
name: LaTeX Release

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

# Für Release-Schreiben notwendig
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Compile LaTeX
        uses: xu-cheng/latex-action@4.0.0
        with:
          root_file: main.tex
          cache: true

      # Optional: Ausgabe umbenennen
      - name: Rename PDF
        run: mv main.pdf "RISE-Handbuch.pdf"

      # Release mit festem Tag "stable" erstellen/aktualisieren und PDF anhängen
      - name: Publish Release (stable)
        uses: ncipollo/release-action@v1
        with:
          tag: stable
          name: Stable build
          body: "Automatisch generiertes PDF aus main branch."
          allowUpdates: true           # Release mit gleichem Tag aktualisieren
          replacesArtifacts: true      # vorhandene Assets ersetzen
          artifacts: "RISE-Handbuch.pdf"
          token: ${{ secrets.GITHUB_TOKEN }}
